/* globals ActInsight, Promise */

ActInsight.KPICustomizerData = function() {
    this.opportunityFields = undefined;
    this.KPIDefinition = undefined;
};

ActInsight.KPICustomizerData.prototype = {
    initialize: function() {
        return this.getKPIDefinition().then(function(kpiDefn) {
            this.KPIDefinition = kpiDefn;
            this.getOpportunityFields();
        }.bind(this));
    },


    getKPIDefinition: function() {
        return Promise.resolve([
            { name : "open_opportunity_count", entity : "opportunity", field : "", operation : "sum", label : "Open Count", isActive:true, isCustom : false },
            { name : "open_opportunity_total_value", entity : "opportunity", field : "totalExtendedAmt", operation : "sum", label : "Total Value", isActive : true, isCustom : false },
            { name : "open_opportunity_weighted_value", entity : "opportunity", field : "weightedAmt", operation : "sum", label : "Weighted Value", isActive : true, isCustom : false },
            { name : "forecasted_opportunity_value", entity : "opportunity", field : "weightedAmt", operation : "sum", label : "Forecast Value", isActive : true, isCustom : false },
            { name : "average_age", entity : "opportunity", field : "", operation : "avg", label : "Average Age", isActive : true, isCustom : false },
            { name : "closed_won_opp_value", entity : "opportunity", field : "totalExtendedAmt", operation : "sum", label : "Closed-Won Value", isActive : true, isCustom : false },
            { name : "closed_lost_opp_value", entity : "opportunity", field : "totalExtendedAmt", operation : "sum", label : "Closed-Lost Value", isActive : true, isCustom : false },
            { name : "average_close_rate", entity : "opportunity", field : "closedPercent", operation : "sum", label : "Close Rate", isActive : true, isCustom : false }
        ]);



    },
    getOpportunityFields: function() {
        return this.getAllOpportunityFields().then(function(allOppFields) {
            var knownFields = this.absractKnownOpportunityFields(allOppFields),
                customFields = this.abstractCustomOpportunityFields(allOppFields);

            this.opportunityFields = knownFields.concat(customFields);

        }.bind(this));
    },
    absractKnownOpportunityFields: function(oppFields) {
        var knownFieldNames = ["productTotal", "weightedTotal", "grossMargin" ];   //todo where are "probabilityPct", "daysOpen"

        var knownFields = _.filter(oppFields, function(field){
            return _.includes(knownFieldNames, field.name);
        });



        return knownFields.map(function(field){
            return {
                id: field.id,
                name: field.name,
                type: field.type,
                displayName: field.displayName,
                picklistId: field.picklist? field.picklist.id : undefined
            };
        });
    },
    abstractCustomOpportunityFields: function(oppFields) {
        var customFields = _.sortBy(oppFields.filter(function(field) {
            var isCustom = field.name.indexOf("customFields/") !== -1,
                dataType = field.type.toLowerCase(),
                isNumber = _.includes(['currency', 'decimal', 'number'], dataType);

            return isCustom && isNumber;
        }), 'name').map(function(field) {
            return {
                id: field.id,
                name: field.name,
                type: field.type,
                displayName: field.displayName,
                picklistId: field.picklist? field.picklist.id : undefined
            };
        });
        return customFields;

    },
    getAllOpportunityFields: function() {
        return Promise.resolve([
            {
                "id": "1916b0b0-a4eb-44e3-8198-2647b06c7910",
                "name": "customFields/opportunity_field_8",
                "columnName": "USER8",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_8",
                "columnType": "Physical",
                "displayName": "Opportunity Field 8",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Datetime",
                "length": 0,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "2018-01-10T16:27:27-07:00",
                "changeEvent": "None://",
                "enterEvent": "None://",
                "leaveEvent": "None://",
                "picklist": null
            },
            {
                "id": "c8220d22-755c-4cc9-9d4a-3f31caf06311",
                "name": "reason",
                "columnName": "CLOSEREASON",
                "recordType": "Opportunity",
                "aliasName": "REASON",
                "columnType": "Physical",
                "displayName": "Reason",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 128,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": {
                    "id": "f72cbf04-72b8-4211-8d55-f5f4cd474d98",
                    "name": "Opportunity Close Reasons",
                    "description": "",
                    "isLimitToList": false,
                    "isMultiSelect": false,
                    "isTypeAhead": true,
                    "showDescription": false
                }
            },
            {
                "id": "b0c3ce44-9a3f-484c-9b46-b048ee3d26c1",
                "name": "productTotal",
                "columnName": "TOTALEXTENDEDAMT",
                "recordType": "Opportunity",
                "aliasName": "TOTAL",
                "columnType": "Physical",
                "displayName": "Total",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Currency",
                "length": 18,
                "scale": 2,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": false,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": true,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "ab77fc14-8ef3-4911-91ce-7acd041d8667",
                "name": "customFields/opportunity_field_6",
                "columnName": "USER6",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_6",
                "columnType": "Physical",
                "displayName": "Opportunity Field 6",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "bb302a4c-a6fb-40a0-8d9d-f9f10938565e",
                "name": "customFields/opportunity_field_7",
                "columnName": "USER7",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_7",
                "columnType": "Physical",
                "displayName": "Opportunity Field 7",
                "tableName": "TBL_OPPORTUNITY",
                "type": "URL Address",
                "length": 64,
                "scale": 0,
                "defaultValue": "",
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "2018-01-10T16:27:52-07:00",
                "changeEvent": "None://",
                "enterEvent": "None://",
                "leaveEvent": "None://",
                "picklist": null
            },
            {
                "id": "216ef347-6146-455c-a239-6ca60a9c1ac2",
                "name": "customFields/opportunity_field_4",
                "columnName": "USER4",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_4",
                "columnType": "Physical",
                "displayName": "Opportunity Field 4",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "46b4f097-942d-4d9b-8839-d81777b67cab",
                "name": "customFields/opportunity_field_5",
                "columnName": "USER5",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_5",
                "columnType": "Physical",
                "displayName": "Opportunity Field 5",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "5e2190aa-bcf4-4138-b5c2-d3e1e733056b",
                "name": "customFields/opportunity_field_2",
                "columnName": "USER2",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_2",
                "columnType": "Physical",
                "displayName": "Opportunity Field 2",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "354b7544-8968-4969-8240-23771307eee9",
                "name": "weightedTotal",
                "columnName": "WEIGHTEDAMT",
                "recordType": "Opportunity",
                "aliasName": "WEIGHTED_TOTAL",
                "columnType": "Physical",
                "displayName": "Weighted Total",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Currency",
                "length": 18,
                "scale": 2,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": false,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": true,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "2761bdea-28b2-4005-aea6-bda61cc0a770",
                "name": "name",
                "columnName": "NAME",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_NAME",
                "columnType": "Physical",
                "displayName": "Opportunity Name",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": "New Opportunity",
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": true,
                "isReadOnly": false,
                "isTracked": true,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "302ebbd8-3615-4f97-9b5d-d56071b15738",
                "name": "customFields/opportunity_field_3",
                "columnName": "USER3",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_3",
                "columnType": "Physical",
                "displayName": "Opportunity Field 3",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "59866461-a20f-403b-b2eb-cbd96c1b8745",
                "name": "customFields/opportunity_field_1",
                "columnName": "USER1",
                "recordType": "Opportunity",
                "aliasName": "OPPORTUNITY_FIELD_1",
                "columnType": "Physical",
                "displayName": "Opportunity Field 1",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "f3d470ee-dd45-4400-9f52-77134d89d9ef",
                "name": "grossMargin",
                "columnName": "GROSSMARGINAMT",
                "recordType": "Opportunity",
                "aliasName": "GROSS_MARGIN",
                "columnType": "Physical",
                "displayName": "Gross Margin",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Currency",
                "length": 18,
                "scale": 2,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": true,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": null
            },
            {
                "id": "9e36f52d-27e6-4c84-8997-60ab0dc4fbb5",
                "name": "competitor",
                "columnName": "COMPETITOR",
                "recordType": "Opportunity",
                "aliasName": "COMPETITOR",
                "columnType": "Physical",
                "displayName": "Competitor",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 128,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": {
                    "id": "aba6bb1b-d5a5-4143-879a-030a04843f1e",
                    "name": "Opportunity Competitors",
                    "description": "",
                    "isLimitToList": false,
                    "isMultiSelect": false,
                    "isTypeAhead": true,
                    "showDescription": false
                }
            },
            {
                "id": "dc7c35bc-dd47-41be-9243-1089169b30f7",
                "name": "customFields/gonna go",
                "columnName": "CUST_GonnaGo_015019479",
                "recordType": "Opportunity",
                "aliasName": "Gonna Go",
                "columnType": "Physical",
                "displayName": "Gonna Go",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Yes/No",
                "length": 0,
                "scale": 0,
                "defaultValue": "False",
                "fieldFormat": "",
                "isAllowBlank": false,
                "isCustom": true,
                "isNullable": false,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2018-01-09T13:50:05-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "None://",
                "enterEvent": "None://",
                "leaveEvent": "None://",
                "picklist": null
            },
            {
                "id": "9bc68f21-bcd3-43a2-b8fe-07c6549f71d0",
                "name": "source",
                "columnName": "SOURCE",
                "recordType": "Opportunity",
                "aliasName": "REFERRED_BY",
                "columnType": "Physical",
                "displayName": "Referred By",
                "tableName": "TBL_OPPORTUNITY",
                "type": "Character",
                "length": 64,
                "scale": 0,
                "defaultValue": null,
                "fieldFormat": "",
                "isAllowBlank": true,
                "isCustom": false,
                "isNullable": true,
                "isPrimary": false,
                "isReadOnly": false,
                "isTracked": false,
                "isVirtual": false,
                "createDate": "2012-01-19T15:23:19-07:00",
                "editDate": "0001-01-01T00:00:00-07:00",
                "changeEvent": "",
                "enterEvent": "",
                "leaveEvent": "",
                "picklist": {
                    "id": "61014261-c17a-44f6-8783-96e94081ae72",
                    "name": "Opportunity Lead Source",
                    "description": "The source which lead to the creation of an Opportunity",
                    "isLimitToList": false,
                    "isMultiSelect": false,
                    "isTypeAhead": true,
                    "showDescription": false
                }
            }
        ]);

    },
    saveKPIDefinition: function() {

    }
};

